python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bart-base_claim_decomp_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bloomz-1b7_claim_decomp_1-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bloomz-1b7_claim_decomp_2-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bart-base_fact_checking_briefs_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bart-base_gpt_generated_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bart-base_gpt_generated_1-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_claim_decomp_fact_checking_briefs_faviq_a_set_faviq_r_set_gpt_generated_5-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_gpt_generated_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_claim_decomp_fact_checking_briefs_faviq_a_set_faviq_r_set_gpt_generated_1-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-flan-t5-base_gpt_generated_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_faviq_r_set_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_claim_decomp_fact_checking_briefs_faviq_a_set_faviq_r_set_gpt_generated_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-flan-t5-base_claim_decomp_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_claim_decomp_fact_checking_briefs_faviq_a_set_faviq_r_set_gpt_generated_3-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_claim_decomp_fact_checking_briefs_faviq_a_set_faviq_r_set_gpt_generated_2-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_fact_checking_briefs_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_faviq_a_set_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-flan-t5-base_fact_checking_briefs_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_claim_decomp_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-flan-t5-base_faviq_a_set_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-flan-t5-base_faviq_r_set_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bloomz-1b1_claim_decomp_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bloomz-1b7_fact_checking_briefs_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bart-base_faviq_r_set_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_faviq_r_set_2-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bart-base_claim_decomp_fact_checking_briefs_faviq_a_set_faviq_r_set_gpt_generated_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bart-base_gpt_generated_2-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_faviq_r_set_1-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-t5-base_claim_decomp_fact_checking_briefs_faviq_a_set_faviq_r_set_gpt_generated_4-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bart-base_faviq_a_set_0-literal-implied-questions.yaml
python3 src/Generate-Question-Test.py --config src/model_configs/literal-implied-test/config-bloomz-1b7_claim_decomp_0-literal-implied-questions.yaml