wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689532196.527536
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 100
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 100
      3:
      - 15
      - 23
      4: 3.9.17
      5: 0.15.5
      6: 4.30.2
      8:
      - 5
