data: data/AVeriTeC
hyper parameters:
  evaluation_strategy: epoch
  fp16: true
  learning_rate: 2e-5
  no_cuda: false
  num_train_epochs: 10
  overwrite_output_dir: true
  per_device_eval_batch_size: 8
  per_device_train_batch_size: 8
  predict_with_generate: true
  weight_decay: 0.3
metrics:
  bleu: true
  rouge: true
model_checkpoint: t5-base
output_dir: models/
test_data:
- data/literal-implied-questions
train_data: data/gpt_generated
wandb_tags:
- query generation
- question generation
